### ISSUE TITLE
Can naptime generate auto api documentation?

### ISSUE THREAD

**Issue by eboto** [coursera/naptime#49]
Just a question here, not a real issue =)

Does naptime have any sort of system that can process your resources and automatically generate documentation?

**Comment by saeta** [comment]
@eboto excellent question! Indeed it can. :-) We haven't yet gotten to open sourcing that component yet, but it should come out in due time.

**Comment by eboto** [comment]
Nice! Thanks for the info. Will look forward to seeing how that piece plays together with the rest of the components.
